from datetime import datetime
from pathlib import Path

from webtrust_auditor.website_scanner import SECURITY_HEADERS
from webtrust_auditor.scoring import calculate_score, count_findings_by_severity


def generate_markdown_report(
    website_result: dict | None,
    email_result: dict | None,
    repository_result: dict | None,
    output_path: str
) -> str:
    """
    Generates a Markdown report from available scan results.
    """
    report_path = Path(output_path)
    report_path.parent.mkdir(parents=True, exist_ok=True)

    markdown_content = build_markdown_report(
        website_result,
        email_result,
        repository_result
    )

    report_path.write_text(markdown_content, encoding="utf-8")

    return str(report_path.resolve())


def build_markdown_report(
    website_result: dict | None,
    email_result: dict | None,
    repository_result: dict | None
) -> str:
    """
    Builds the complete Markdown report.
    """
    scan_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = []

    lines.append("# WebTrust Auditor Report")
    lines.append("")
    lines.append("## Scan Information")
    lines.append("")
    lines.append(f"- Scan date: {scan_date}")

    if website_result:
        lines.append(f"- Target URL: {safe_text(website_result.get('target_url'))}")
        lines.append(f"- Final URL: {safe_text(website_result.get('final_url'))}")
        lines.append(f"- Status code: {safe_text(website_result.get('status_code'))}")
        lines.append(f"- HTTPS enabled: {'Yes' if website_result.get('is_https') else 'No'}")

    if email_result:
        lines.append(f"- Email domain: {safe_text(email_result.get('domain'))}")

    if repository_result:
        lines.append(f"- Repository path: {safe_text(repository_result.get('repo_path'))}")

    lines.append("")

    if website_result:
        append_website_section(lines, website_result)

    if email_result:
        append_email_section(lines, email_result)

    if repository_result:
        append_repository_section(lines, repository_result)

    lines.append("## Notes")
    lines.append("")
    lines.append(
        "This report is generated by WebTrust Auditor. The tool performs passive checks only. "
        "It does not attack, exploit, brute-force, send emails or modify the target system."
    )
    lines.append("")

    return "\n".join(lines)


def append_website_section(lines: list, result: dict) -> None:
    """
    Adds website scan results to the Markdown report.
    """
    lines.append("## Website Security Results")
    lines.append("")

    if result.get("error"):
        lines.append("### Error")
        lines.append("")
        lines.append(f"The website scan could not be completed: `{safe_text(result['error'])}`")
        lines.append("")
        return

    findings = result.get("findings", [])
    score_result = calculate_score(findings)
    severity_counts = count_findings_by_severity(findings)

    lines.append("### Website Score")
    lines.append("")
    lines.append(f"**Website Security Score:** {score_result['score']} / 100")
    lines.append("")
    lines.append(f"**Rating:** {score_result['rating']}")
    lines.append("")
    lines.append(f"**Total penalty:** -{score_result['total_penalty']} points")
    lines.append("")

    lines.append("### Website Summary")
    lines.append("")

    if not findings:
        lines.append("No basic website security findings were detected.")
    else:
        lines.append(
            f"The website scan detected **{len(findings)} finding(s)** "
            "related to basic website security readiness."
        )

    lines.append("")

    append_severity_table(lines, severity_counts)

    lines.append("### Security Header Status")
    lines.append("")
    lines.append("| Header | Status |")
    lines.append("|---|---|")

    headers_lower = result.get("headers_lower", {})

    if not headers_lower:
        headers_lower = {
            str(header_name).lower(): header_value
            for header_name, header_value in result.get("headers", {}).items()
        }

    for header_name in SECURITY_HEADERS.keys():
        status = "Present" if header_name.lower() in headers_lower else "Missing"
        lines.append(f"| `{header_name}` | {status} |")

        lines.append("")

    append_findings_sections(lines, findings, "Website")


def append_email_section(lines: list, result: dict) -> None:
    """
    Adds email/domain scan results to the Markdown report.
    """
    lines.append("## Email / Domain Security Results")
    lines.append("")

    if result.get("error"):
        lines.append("### Error")
        lines.append("")
        lines.append(f"The email/domain scan could not be completed: `{safe_text(result['error'])}`")
        lines.append("")
        return

    findings = result.get("findings", [])
    score_result = calculate_score(findings)
    severity_counts = count_findings_by_severity(findings)

    lines.append("### Email Domain Score")
    lines.append("")
    lines.append(f"**Email Domain Security Score:** {score_result['score']} / 100")
    lines.append("")
    lines.append(f"**Rating:** {score_result['rating']}")
    lines.append("")
    lines.append(f"**Total penalty:** -{score_result['total_penalty']} points")
    lines.append("")

    lines.append("### DNS Record Summary")
    lines.append("")
    lines.append(f"- Domain: {safe_text(result.get('domain'))}")
    lines.append(f"- MX records found: {len(result.get('mx_records', []))}")
    lines.append(f"- SPF records found: {len(result.get('spf_records', []))}")
    lines.append(f"- DMARC record found: {'Yes' if result.get('dmarc_record') else 'No'}")
    lines.append(f"- DMARC policy: {safe_text(result.get('dmarc_policy'))}")
    lines.append(f"- DKIM selector: {safe_text(result.get('dkim_selector'))}")
    lines.append(f"- DKIM record found: {'Yes' if result.get('dkim_record') else 'No'}")
    lines.append("")

    lines.append("### MX Records")
    lines.append("")

    mx_records = result.get("mx_records", [])

    if mx_records:
        for record in mx_records:
            lines.append(f"- `{safe_text(record)}`")
    else:
        lines.append("No MX records found.")

    lines.append("")

    lines.append("### SPF Records")
    lines.append("")

    spf_records = result.get("spf_records", [])

    if spf_records:
        for record in spf_records:
            lines.append(f"- `{safe_text(record)}`")
    else:
        lines.append("No SPF records found.")

    lines.append("")

    lines.append("### DMARC Record")
    lines.append("")

    if result.get("dmarc_record"):
        lines.append(f"`{safe_text(result.get('dmarc_record'))}`")
    else:
        lines.append("No DMARC record found.")

    lines.append("")

    append_severity_table(lines, severity_counts)
    append_findings_sections(lines, findings, "Email / Domain")


def append_repository_section(lines: list, result: dict) -> None:
    """
    Adds local repository hygiene scan results to the Markdown report.
    """
    lines.append("## Repository Hygiene Results")
    lines.append("")

    if result.get("error"):
        lines.append("### Error")
        lines.append("")
        lines.append(f"The repository scan could not be completed: `{safe_text(result['error'])}`")
        lines.append("")
        return

    findings = result.get("findings", [])
    score_result = calculate_score(findings)
    severity_counts = count_findings_by_severity(findings)
    summary = result.get("summary", {})

    lines.append("### Repository Score")
    lines.append("")
    lines.append(f"**Repository Hygiene Score:** {score_result['score']} / 100")
    lines.append("")
    lines.append(f"**Rating:** {score_result['rating']}")
    lines.append("")
    lines.append(f"**Total penalty:** -{score_result['total_penalty']} points")
    lines.append("")

    lines.append("### Repository Summary")
    lines.append("")
    lines.append(f"- Repository path: {safe_text(result.get('repo_path'))}")
    lines.append(f"- Files checked: {safe_text(result.get('files_checked'))}")
    lines.append(f"- .gitignore exists: {'Yes' if summary.get('gitignore_exists') else 'No'}")
    lines.append(f"- README.md exists: {'Yes' if summary.get('readme_exists') else 'No'}")
    lines.append(f"- Dockerfile exists: {'Yes' if summary.get('dockerfile_exists') else 'No'}")
    lines.append(f"- .dockerignore exists: {'Yes' if summary.get('dockerignore_exists') else 'No'}")
    lines.append(f"- Sensitive files found: {safe_text(summary.get('sensitive_files_found'))}")
    lines.append(f"- Database files found: {safe_text(summary.get('database_files_found'))}")
    lines.append(f"- Secret keyword hits: {safe_text(summary.get('secret_keyword_hits'))}")
    lines.append("")

    append_severity_table(lines, severity_counts)
    append_findings_sections(lines, findings, "Repository")


def append_severity_table(lines: list, severity_counts: dict) -> None:
    """
    Adds a severity summary table.
    """
    lines.append("### Findings by Severity")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    lines.append(f"| High | {severity_counts['High']} |")
    lines.append(f"| Medium | {severity_counts['Medium']} |")
    lines.append(f"| Low | {severity_counts['Low']} |")
    lines.append(f"| Info | {severity_counts['Info']} |")
    lines.append("")


def append_findings_sections(lines: list, findings: list, section_name: str) -> None:
    """
    Adds findings overview, score deductions and detailed findings.
    """
    lines.append(f"### {section_name} Findings Overview")
    lines.append("")

    if not findings:
        lines.append("No findings to display.")
        lines.append("")
    else:
        lines.append("| Severity | Finding | Evidence |")
        lines.append("|---|---|---|")

        for finding in findings:
            severity = safe_text(finding.get("severity"))
            title = safe_text(finding.get("title"))
            evidence = safe_text(finding.get("evidence"))
            lines.append(f"| {severity} | {title} | {evidence} |")

        lines.append("")

    score_result = calculate_score(findings)

    lines.append(f"### {section_name} Score Deductions")
    lines.append("")

    if not score_result["deductions"]:
        lines.append("No score deductions were applied.")
        lines.append("")
    else:
        lines.append("| Severity | Finding | Penalty |")
        lines.append("|---|---|---|")

        for deduction in score_result["deductions"]:
            lines.append(
                f"| {safe_text(deduction['severity'])} | "
                f"{safe_text(deduction['title'])} | "
                f"-{deduction['penalty']} |"
            )

        lines.append("")

    lines.append(f"### {section_name} Detailed Findings")
    lines.append("")

    if not findings:
        lines.append("No detailed findings to display.")
        lines.append("")
    else:
        for index, finding in enumerate(findings, start=1):
            lines.append(f"#### {index}. {safe_text(finding.get('title'))}")
            lines.append("")
            lines.append(f"**Severity:** {safe_text(finding.get('severity'))}")
            lines.append("")
            lines.append("**Evidence:**")
            lines.append("")
            lines.append(f"{safe_text(finding.get('evidence'))}")
            lines.append("")
            lines.append("**Why it matters:**")
            lines.append("")
            lines.append(f"{safe_text(finding.get('why'))}")
            lines.append("")
            lines.append("**Recommendation:**")
            lines.append("")
            lines.append(f"{safe_text(finding.get('recommendation'))}")
            lines.append("")


def safe_text(value) -> str:
    """
    Converts values to safe Markdown text.
    Also prevents table formatting issues by replacing pipe characters.
    """
    if value is None:
        return "N/A"

    return str(value).replace("|", "\\|")